### PR TITLE
sort alum by degree and year

### PR DESCRIPTION
**Pull request by rachitnigam**

### CODE REVIEW

**Comment by sampsyo** [comment]
Seems reasonable! Any chance you could leave a comment in there saying what `sort` values people are supposed to have for the alumni section?

(I also assume it's not feasible to leave out those `sort: 0`s on the sections where we don't care, right? Like, I suppose `groupby` would get mad, but I wish it wouldn't…)

**Comment by rachitnigam** [comment]
Added comment! It might be possible but I can't figure out how to apply a filter to a dictionary. I think one, simpler solution overall might be to use a function passed into the template directly but again that is a bunch of work. I'll merge this now and open an issue to improve it.

**Comment by rachitnigam** [comment]
Opened https://github.com/cucapra/capra-public/issues/18 to talk about the possible fix

**Comment by sampsyo** [comment]
Awesome; thanks!

**Pull request merged**
