### PR TITLE
multiple columns at the end for alumni

### PR DESCRIPTION
**Pull request by rachitnigam**
In the limit, we will have far more "alumni" than people. This PR creates a dedicated div for the alumni section and splits it into multiple columns.

Screen Shot 2021-02-27 at 11 21 06 AM

### CODE REVIEW

**Comment by sampsyo** [comment]
Thanks!! Indeed, something like this is definitely necessary. This could grow in an unbounded way!

I think multiple columns below the current columns could work well. A reason I have avoided it until now is that it creates a weird white chunk in the lower-right of the grid. But the alternative is worse, so it still seems like the right thing to do? In general, I have never _really_ loved this whole column-based thing because of all these trade-offs.

Anyway, the general idea seems good. But because the new columns in this PR are evenly divided instead of using the same grid as the old columns, they don't quite line up perfectly (see how "Harrison" is a little to the right of "Samuel"?). Do you think there's an easy way to get these to match exactly?

**Comment by rachitnigam** [comment]
So, annoyingly, the answer seems to be no. The `columns` nonsense only allows for even spacing between and it responsively reduces space between columns.

**Comment by sampsyo** [comment]
Arg! Maybe there's some way to make the stuff above use the *same* kind of columns too...

**Comment by rachitnigam** [comment]
Used some `max-width` hacking to align things:
Screen Shot 2021-03-01 at 8 46 33 PM

**Comment by sampsyo** [comment]
Wahoo! Thanks!!!! :tada: This is awesome.

**Pull request merged**
